#! /usr/bin/env python3
# -*- coding:utf-8 -*-

import cgi
import html

print("Content-type: text/html\n")

print("""
<style>
        body {
            background: aliceblue;
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
        }

        table {
            border: 1px solid #5a5a5a;
            margin: 15px auto auto;
            width: 50%;
            text-align: center;
            box-shadow: 5px 5px 15px rgba(45, 45, 45, 0.61);
            background: #ebf1ff;
            border-collapse: collapse;
        }

        th {
            height: 30px;
            background: #d7e3ff;
            box-shadow: 0 5px 3px rgba(121, 121, 121, 0.35);
        }

        td{
            padding: 3px;
        }

        input[type="submit"] {
            width: 20%;
            height: 25px;
        }
    </style>
    """)

formStorage = cgi.FieldStorage()
country = html.escape(formStorage.getfirst("country", "country"))
city = html.escape(formStorage.getfirst("city", "city"))
is_lunches_enabled = html.escape(formStorage.getfirst("is-lunches-enabled", "false"))
count_days = html.escape(formStorage.getfirst("days", "5"))

print(f"""
<form action="/cgi-bin/form-handler.py">
    <table>
        <tr>
            <th>Label</th>
            <th>Value</th>
        </tr>
        <tr>
            <td>City</td>
            <td>{city}</td>
        </tr>
        <tr>
            <td>Country</td>
            <td>{country}</td>
        </tr>
        <tr>
            <td>Is lunches enabled</td>
            <td>{is_lunches_enabled}</td>
        </tr>
        <tr>
            <td>Count of days</td>
            <td>{count_days}</td>
        </tr>
    </table>
</form>

</body>
</html>
""")
